services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: demo_spring
      MYSQL_ROOT_PASSWORD: pass@123
      MYSQL_PASSWORD: pass@123
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    image: demo_spring
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo_spring?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass@123

volumes:
  db-data:
